
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: trul
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: root
    password: mercado_acoes
    platform: h2
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update